.\" unversioned-python.8
.TH UNVERSIONED-PYTHON 8 "17 September 2018"
.SH NAME
unversioned-python \- info on how to set up the `python` command.
.SH SYNOPSIS
.B unversioned-python
.SH DESCRIPTION
.B unversioned-python
The "unversioned" `python` command (/usr/bin/python) is missing by default.
We recommend using `python3` or `python2` instead.
If using the explicit versioned command is inconvenient,
you can use `alternatives` to configure `python` to launch
either Python 3 or Python 2.

Note: The `python3` or `python2` package needs to be installed before its
functionality is selected.

.SH EXAXPLES
.B alternatives
.B --config
.IR python

    Interactively select what the `python` command runs.


.B alternatives
.B --set
.IR python
.IR /usr/bin/python3

    Configure the `python` command to run Python 3

    Note: this is non-standard behavior according to [PEP 394].


.B alternatives
.B --set
.IR python
.IR /usr/bin/python2

    Configure the `python` command to run Python 2

    Note: please review the support lifecycle of python2 before relying on it


.B alternatives
.B --auto
.IR python

    Undo configuration changes and revert to the default (missing `python` command)


.SH LINKS

.B [PEP 394]:
.IR https://www.python.org/dev/peps/pep-0394/

